spring:
  application:
    name: ottimizza-eduardo-testepleno

  datasource:
    url: jdbc:postgresql://localhost:5432/teste-pleno-kanban
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher